
project_id = "znncfayiwfamujvrprvf"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions]
[functions.create-stripe-payment]
verify_jwt = false

[functions.capture-stripe-payment] 
verify_jwt = true

[functions.process-escrow-payment]
verify_jwt = true

[functions.send-email-notification]
verify_jwt = true

[functions.send-response-email]
verify_jwt = true

[functions.create-stripe-connect-account]
verify_jwt = false

[functions.stripe-connect-webhook]
verify_jwt = false
